name: CS Server Sync and Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'server-files/addons/**'
      - '!.github/workflows/**'
  workflow_dispatch:

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Download from server (on manual trigger)
      - name: Sync from server
        if: github.event_name == 'workflow_dispatch'
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: 2022
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          localDir: './server-files/addons'
          remoteDir: '/cstrike/addons'
          download: true
          forceDownload: true # Додано для примусового оновлення
          removeExtraFiles: false # Не видаляти файли
          dryRun: false # Виконувати реальні дії

      # Clean .gitkeep files after download
      - name: Clean .gitkeep files
        if: github.event_name == 'workflow_dispatch'
        run: |
          find ./server-files/addons -name ".gitkeep" -type f -delete

      # Commit downloaded files
      - name: Commit changes
        if: github.event_name == 'workflow_dispatch'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add server-files/addons/
          git status
          git diff --staged --quiet || (git commit -m "Sync files from server" && git push)

      # Deploy to server (on push)
      - name: Deploy changes
        if: github.event_name == 'push'
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: 2022
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          localDir: './server-files/addons'
          remoteDir: '/cstrike/addons'
          forceUpload: true
          removeExtraFiles: false