name: CS Server Sync and Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'server-files/**'
  workflow_dispatch:

jobs:

  sync-from-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Download files from server
      uses: wangyucode/sftp-upload-action@v2.0.2
      with:
        host: ${{ secrets.SFTP_HOST }}
        port: 2022
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        localDir: './server-files'
        remoteDir: '/cstrike/addons'
        download: true

    - name: Commit changes
      if: steps.git-status.outputs.clean == 'false'
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add server-files/
        git diff --staged --quiet || git commit -m "Sync server files"
        git push || echo "No changes to push"

  deploy-to-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Deploy to server
      uses: wangyucode/sftp-upload-action@v2.0.2
      with:
        host: ${{ secrets.SFTP_HOST }}
        port: 2022
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        localDir: './server-files'
        remoteDir: '/cstrike/addons'
        forceUpload: true