name: CS Server Sync and Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'working-files/**'
      - 'server-files/**'
  workflow_dispatch:

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Створення директорій якщо їх немає
      - name: Ensure directories exist
        run: |
          mkdir -p server-files/addons/amxmodx
          mkdir -p server-files/addons/metamod

      # Синхронізація з сервера
      - name: Download from server
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: 2022
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          localDir: 'server-files'
          remoteDir: '/cstrike/addons'
          download: true
          forceUpload: false

      # Перевірка змін
      - name: Check for changes
        id: check
        run: |
          git status
          git diff --quiet server-files/ || echo "has_changes=true" >> $GITHUB_OUTPUT

      # Коміт змін якщо вони є
      - name: Commit changes
        if: steps.check.outputs.has_changes == 'true'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add server-files/
          git commit -m "Update server files from sync"
          git push