name: CS Server Sync and Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'server-files/**'
  workflow_dispatch:

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Download from server (on manual trigger)
      - name: Sync from server
        if: github.event_name == 'workflow_dispatch'
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: 2022
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          localDir: './server-files'
          remoteDir: '/cstrike/addons'
          download: true

      # Deploy to server (on push)
      - name: Deploy changes
        if: github.event_name == 'push'
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: 2022
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          localDir: './server-files'
          remoteDir: '/cstrike/addons'
          forceUpload: true

      # Commit downloaded files
      - name: Commit changes
        if: github.event_name == 'workflow_dispatch'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add server-files/
          git diff --staged --quiet || git commit -m "Update server files from sync"
          git push || echo "No changes to push"