name: CS Server Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'server-files/addons/**'
      - '!.github/workflows/**'
  workflow_dispatch:

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Download from server (on manual trigger)
      - name: Create directories
        if: github.event_name == 'workflow_dispatch'
        run: |
          mkdir -p server-files/addons/amxmodx
          mkdir -p server-files/addons/metamod

      - name: Sync from server
        if: github.event_name == 'workflow_dispatch'
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: 2022
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          localDir: './server-files/addons'
          remoteDir: 'cstrike/addons'
          forceUpload: false
          dryRun: true # Спочатку подивимось що буде синхронізуватися

      # Commit downloaded files
      - name: Commit changes
        if: github.event_name == 'workflow_dispatch'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
          git add -f server-files/addons/
          git status
          git diff --staged --quiet || (git commit -m "Sync files from server" && git push)

      # Deploy to server (on push)
      - name: Deploy to server
        if: github.event_name == 'push'
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: 2022
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          localDir: './server-files/addons'
          remoteDir: 'cstrike/addons'
          forceUpload: false # Змінено на false для безпеки
          dryRun: true # Спочатку в режимі перегляду