name: CS Server Sync and Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'server-files/addons/**'
      - '!.github/workflows/**'
  workflow_dispatch:

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      # Download from server (on manual trigger)
      - name: Sync from server
        if: github.event_name == 'workflow_dispatch'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 2022
          protocol: sftp
          local-dir: ./server-files/addons/
          server-dir: /cstrike/addons/
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
          download: true

      # Commit downloaded files
      - name: Commit changes
        if: github.event_name == 'workflow_dispatch'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
          git add server-files/addons/
          git status
          git diff --staged --quiet || (git commit -m "Sync files from server" && git push)

      # Deploy to server (on push)
      - name: Deploy changes
        if: github.event_name == 'push'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 2022
          protocol: sftp
          local-dir: ./server-files/addons/
          server-dir: /cstrike/addons/
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**