name: CS Server Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'server-files/addons/**'
      - '!.github/workflows/**'
  workflow_dispatch:

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      # Install lftp
      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      # Create base structure (on manual trigger)
      - name: Create base structure
        if: github.event_name == 'workflow_dispatch'
        run: |
          mkdir -p server-files/addons/amxmodx/{configs,data,dlls,logs,modules,plugins,scripting}
          mkdir -p server-files/addons/metamod/dlls

      # Download from server (on manual trigger)
      - name: Sync from server
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "set sftp:auto-confirm yes" > lftp_script
          echo "open -u ${{ secrets.SFTP_USERNAME }},${{ secrets.SFTP_PASSWORD }} sftp://${{ secrets.SFTP_HOST }}:2022" >> lftp_script
          echo "mirror --verbose --delete cstrike/addons $GITHUB_WORKSPACE/server-files/addons" >> lftp_script
          cat lftp_script | grep -v ${{ secrets.SFTP_PASSWORD }}
          lftp -f lftp_script
          rm lftp_script
          ls -la server-files/addons/

      # Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      # Commit downloaded files
      - name: Commit changes
        if: github.event_name == 'workflow_dispatch'
        run: |
          git add -A server-files/addons/
          git status
          git diff --cached --name-status
          git commit -m "Sync files from server" || echo "No changes to commit"
          git push || echo "No changes to push"

      # Deploy to server (on push)
      - name: Deploy to server
        if: github.event_name == 'push'
        run: |
          echo "set sftp:auto-confirm yes" > lftp_script
          echo "open -u ${{ secrets.SFTP_USERNAME }},${{ secrets.SFTP_PASSWORD }} sftp://${{ secrets.SFTP_HOST }}:2022" >> lftp_script
          echo "mirror --verbose --reverse --delete $GITHUB_WORKSPACE/server-files/addons cstrike/addons" >> lftp_script
          cat lftp_script | grep -v ${{ secrets.SFTP_PASSWORD }}
          lftp -f lftp_script
          rm lftp_script
